-- SOU+BLU — Propostas de Crédito — MySQL Locaweb (tabela separada de proposals)
-- Rode via: GET /api/migrate-credito.php (X-API-Key) ou php api/migrate-credito.php local

CREATE TABLE IF NOT EXISTS `credit_proposals` (
  `id` VARCHAR(64) NOT NULL,
  `protocolo` VARCHAR(32) NOT NULL,
  `employee_id` VARCHAR(64) NOT NULL,
  `employee_name` VARCHAR(255) NULL,
  `vendor_id` VARCHAR(64) NULL,
  `vendor_name` VARCHAR(255) NULL,
  `cpf` VARCHAR(11) NOT NULL,
  `nome` VARCHAR(255) NOT NULL,
  `valor_solicitado` DECIMAL(12,2) NOT NULL DEFAULT 0,
  `valor_aprovado` DECIMAL(12,2) NULL,
  `valor_parcela` DECIMAL(12,2) NULL,
  `valor_final` DECIMAL(12,2) NULL,
  `conta_santander` VARCHAR(8) NULL,
  `forma_pagamento` VARCHAR(64) NULL,
  `banco` VARCHAR(128) NULL,
  `agencia` VARCHAR(32) NULL,
  `conta_corrente` VARCHAR(32) NULL,
  `contato1` VARCHAR(32) NULL,
  `contato2` VARCHAR(32) NULL,
  `observacao` TEXT NULL,
  `avalista_cpf` VARCHAR(11) NULL,
  `avalista_nome` VARCHAR(255) NULL,
  `avalista_telefone` VARCHAR(32) NULL,
  `status` VARCHAR(64) NOT NULL DEFAULT 'AG. ANÁLISE',
  `esteira` JSON NULL,
  `retorno` JSON NULL,
  `attachments` JSON NULL,
  `history` JSON NULL,
  `meta` JSON NULL,
  `legacy_proposal_id` VARCHAR(64) NULL,
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uq_credit_protocolo` (`protocolo`),
  KEY `idx_credit_employee` (`employee_id`, `created_at`),
  KEY `idx_credit_status` (`status`, `updated_at`),
  KEY `idx_credit_cpf` (`cpf`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
